// Generates CARDS.md: every card and its upgrade, rendered by the engine itself, plus a
// starter-deck balance table. The text in CARDS.md is exactly what the game shows.
//   node tools/catalogue.js
import { writeFileSync } from 'node:fs';
import { CARDS, CARDS_BY_HERO } from '../src/content/cards.js';
import { REWARD_POOLS } from '../src/content/rewards.js';
import { HEROES } from '../src/content/heroes.js';
import { ENEMIES, FLOOR_POOLS } from '../src/content/enemies.js';
import { getCard, cardTextPlain } from '../src/engine/cards.js';
import { createRun } from '../src/engine/run.js';
import { createCombat, playCard, endTurn, reroll, playability, resolveChoice } from '../src/engine/combat.js';
import { affinityMet } from '../src/engine/dice.js';
import { createRng, int, pick } from '../src/engine/rng.js';

const TYPE = { attack: 'Attack', skill: 'Skill', power: 'Power' };
const cell = (s) => String(s).replace(/\|/g, '\\|');

function rarityIn(hero, key) {
  const pool = REWARD_POOLS[hero];
  if (!pool) return '';
  return ['common', 'uncommon', 'rare'].find((r) => pool[r].includes(key)) ?? '';
}

function cardRow(key, hero) {
  const a = getCard(key);
  const b = getCard(key + '+');
  const starter = HEROES[hero]?.starterDeck.includes(key);
  const tags = [starter ? 'starter' : '', rarityIn(hero, key)].filter(Boolean).join(', ');
  const kind = TYPE[a.type] + (a.exhausts ? ' · Exhaust' : '');
  const upCost = b.cost !== a.cost ? `**${b.cost}** ` : '';
  const flag = CARDS[key].identicalUpgrade ? ' ⚠ *identical upgrade — see notes*' : '';
  return `| ${a.emoji} **${cell(a.name)}** \`${key}\` | ${a.cost} | ${kind} | ${tags} | ${cell(cardTextPlain(a))} | ${upCost}${cell(cardTextPlain(b))}${flag} |`;
}

// ── Balance: a simple greedy agent plays each starter deck against each Floor 1 enemy ──

function agentTurn(c, rng) {
  const hero = HEROES[c.run.heroKey];
  if (!affinityMet(c, hero.affinity) && c.die.rerollsLeft > 0) reroll(c);
  for (let guard = 0; guard < 40 && c.phase === 'player'; guard++) {
    if (c.pending) {
      const p = c.pending;
      if (p.kind === 'die') resolveChoice(c, p.max);
      else resolveChoice(c, p.cards.slice(0, p.count).map((x) => x.uid));
      continue;
    }
    const options = c.piles.hand.filter((card) => {
      const check = playability(c, card);
      return check.ok && !check.warning;
    });
    if (!options.length) break;
    playCard(c, pick(rng, options).uid);
  }
  if (c.phase === 'player' && !c.pending) endTurn(c);
}

function balance(hero, enemyId, n = 300) {
  let wins = 0, turns = 0, hpLost = 0;
  for (let seed = 1; seed <= n; seed++) {
    const run = createRun({ heroKey: hero, seed });
    const c = createCombat(run, enemyId);
    const rng = createRng(seed * 31);
    while (c.phase === 'player' && c.turn < 100) agentTurn(c, rng);
    if (c.phase === 'won') {
      wins += 1;
      turns += c.turn;
      hpLost += run.maxHp - c.player.hp;
    }
  }
  return { win: Math.round((wins / n) * 100), turns: wins ? (turns / wins).toFixed(1) : '–', hpLost: wins ? Math.round(hpLost / wins) : '–' };
}

// ── Document ──

const heroes = Object.keys(HEROES);
const out = [];
out.push('# Card catalogue — claude-version', '');
out.push('*Generated by `node tools/catalogue.js`. Do not edit by hand: every line of card text below is');
out.push('rendered by the game engine from the same params the effects use.*', '');
out.push('Upgrade column: the full upgraded text; a **bold** number before it is a changed cost.');
out.push('Formula values ("2× your roll") show their live number in combat.', '');

const total = Object.keys(CARDS).length;
out.push(`**${total} cards**, each with an upgrade: ${heroes.map((h) => `${HEROES[h].name} ${CARDS_BY_HERO[h].length}`).join(', ')}, shared ${CARDS_BY_HERO.shared.length}.`, '');

for (const hero of heroes) {
  const h = HEROES[hero];
  out.push(`## ${h.emoji} ${h.name}`, '');
  out.push(`${h.hp} HP · d${h.die.sides}${h.die.minRoll ? ` (min ${h.die.minRoll})` : ''} · affinity **${h.affinity}** · ${h.blurb}`, '');
  out.push(`Starter deck: ${h.starterDeck.map((k) => getCard(k).name).join(', ')}.`, '');
  out.push('| Card | Cost | Type | Pool | Text | Upgraded |', '|---|---|---|---|---|---|');
  for (const key of CARDS_BY_HERO[hero]) out.push(cardRow(key, hero));
  const shared = [...REWARD_POOLS[hero].common, ...REWARD_POOLS[hero].uncommon, ...REWARD_POOLS[hero].rare]
    .filter((k) => CARDS_BY_HERO.shared.includes(k));
  if (shared.length) out.push('', `Shared cards in this pool: ${shared.map((k) => `${getCard(k).name} (${rarityIn(hero, k)})`).join(', ')}.`);
  out.push('');
}

out.push('## Shared cards', '', '| Card | Cost | Type | Pool | Text | Upgraded |', '|---|---|---|---|---|---|');
for (const key of CARDS_BY_HERO.shared) out.push(cardRow(key, ''));
out.push('');

out.push('## Notes for review', '');
for (const [key, def] of Object.entries(CARDS)) {
  if (def.identicalUpgrade) out.push(`- ⚠ **${def.name}+** — identical upgrade. ${def.identicalUpgrade}`);
}
out.push('');

out.push('## Starter-deck balance (Floor 1)', '');
out.push('Each hero\'s unmodified starter deck at full HP, 300 seeded fights per cell, played by a simple');
out.push('greedy agent (rerolls a missed affinity, then plays random affordable cards; never plays into an');
out.push('unmet condition). Win % / average turns to win / average HP lost in a win. A human should beat these.', '');
const floor = FLOOR_POOLS[1];
const enemyIds = [...floor.easy, ...floor.standard, ...floor.elite];
out.push(`| Hero | ${enemyIds.map((id) => ENEMIES[id].name + (floor.easy.includes(id) ? ' (easy)' : floor.elite.includes(id) ? ' (elite)' : '')).join(' | ')} |`);
out.push(`|---|${enemyIds.map(() => '---').join('|')}|`);
for (const hero of heroes) {
  const cells = enemyIds.map((id) => {
    const b = balance(hero, id);
    return `${b.win}% / ${b.turns} / ${b.hpLost}`;
  });
  out.push(`| ${HEROES[hero].name} | ${cells.join(' | ')} |`);
}
out.push('');

writeFileSync(new URL('../CARDS.md', import.meta.url), out.join('\n'));
console.log(`CARDS.md written: ${total} cards.`);
