// Generates CARDS.md: every card and its upgrade, rendered by the engine itself, plus a
// three balance tables (Floor 1, every floor, and whole runs). The text in CARDS.md is exactly what the
// game shows.
//   node tools/catalogue.js
import { writeFileSync } from 'node:fs';
import { CARDS, CARDS_BY_HERO } from '../src/content/cards.js';
import { REWARD_POOLS } from '../src/content/rewards.js';
import { HEROES } from '../src/content/heroes.js';
import { ENEMIES, FLOOR_POOLS, COMPANION_BOSSES } from '../src/content/enemies.js';
import { getCard, cardTextPlain } from '../src/engine/cards.js';
import {
  createRun, choosePath, chooseDoor, doorOptions, finishCombat, takeCardReward, skipCardReward, restOptions,
  restHeal, restUpgrade, restRemove, restLeave, shopLeave, soulBuy, soulLeave, leaveRoom, leaveDieCache, faceBoss,
  leaveFloorClear,
} from '../src/engine/run.js';
import { soulCost } from '../src/engine/soul.js';
import { canUpgrade } from '../src/engine/shop.js';
import { createCombat, playCard, endTurn, reroll, playability, resolveChoice } from '../src/engine/combat.js';
import { affinityMet, affinityLine } from '../src/engine/dice.js';
import { DICE, STARTING_DIE } from '../src/content/dice.js';
import { createRng, int, pick } from '../src/engine/rng.js';

const TYPE = { attack: 'Attack', skill: 'Skill', power: 'Power' };
const cell = (s) => String(s).replace(/\|/g, '\\|');

function rarityIn(hero, key) {
  const pool = REWARD_POOLS[hero];
  if (!pool) return '';
  return ['common', 'uncommon', 'rare'].find((r) => pool[r].includes(key)) ?? '';
}

function cardRow(key, hero) {
  const a = getCard(key);
  const b = getCard(key + '+');
  const starter = HEROES[hero]?.starterDeck.includes(key);
  const tags = [starter ? 'starter' : '', rarityIn(hero, key)].filter(Boolean).join(', ');
  const kind = TYPE[a.type] + (a.exhausts ? ' · Exhaust' : '');
  const upCost = b.cost !== a.cost ? `**${b.cost}** ` : '';
  const flag = CARDS[key].identicalUpgrade ? ' ⚠ *identical upgrade — see notes*' : '';
  return `| ${a.emoji} **${cell(a.name)}** \`${key}\` | ${a.cost} | ${kind} | ${tags} | ${cell(cardTextPlain(a))} | ${upCost}${cell(cardTextPlain(b))}${flag} |`;
}

// ── Balance: a simple greedy agent plays each starter deck against each Floor 1 enemy ──

function agentTurn(c, rng) {
  const hero = HEROES[c.run.heroKey];
  if (!affinityMet(c, hero.affinity) && c.die.rerollsLeft > 0) reroll(c);
  for (let guard = 0; guard < 40 && c.phase === 'player'; guard++) {
    if (c.pending) {
      const p = c.pending;
      if (p.kind === 'die') resolveChoice(c, p.max);
      else resolveChoice(c, p.cards.slice(0, p.count).map((x) => x.uid));
      continue;
    }
    const options = c.piles.hand.filter((card) => {
      const check = playability(c, card);
      return check.ok && !check.warning;
    });
    if (!options.length) break;
    playCard(c, pick(rng, options).uid);
  }
  if (c.phase === 'player' && !c.pending) endTurn(c);
}

function balance(hero, enemyId, n = 300) {
  let wins = 0, turns = 0, hpLost = 0;
  for (let seed = 1; seed <= n; seed++) {
    const run = createRun({ heroKey: hero, seed });
    const c = createCombat(run, enemyId);
    const rng = createRng(seed * 31);
    while (c.phase === 'player' && c.turn < 100) agentTurn(c, rng);
    if (c.phase === 'won') {
      wins += 1;
      turns += c.turn;
      hpLost += run.maxHp - c.player.hp;
    }
  }
  return { win: Math.round((wins / n) * 100), turns: wins ? (turns / wins).toFixed(1) : '–', hpLost: wins ? Math.round(hpLost / wins) : '–' };
}

// ── Document ──

const heroes = Object.keys(HEROES);
const out = [];
out.push('# Card catalogue — claude-version', '');
out.push('*Generated by `node tools/catalogue.js`. Do not edit by hand: every line of card text below is');
out.push('rendered by the game engine from the same params the effects use.*', '');
out.push('Upgrade column: the full upgraded text; a **bold** number before it is a changed cost.');
out.push('Formula values ("2× your roll") show their live number in combat.', '');

const total = Object.keys(CARDS).length;
out.push(`**${total} cards**, each with an upgrade: ${heroes.map((h) => `${HEROES[h].name} ${CARDS_BY_HERO[h].length}`).join(', ')}, shared ${CARDS_BY_HERO.shared.length}.`, '');

for (const hero of heroes) {
  const h = HEROES[hero];
  out.push(`## ${h.emoji} ${h.name}`, '');
  const start = DICE[STARTING_DIE];
  out.push(`${h.hp} HP · ${start.id}${h.minRoll ? ` (min roll ${h.minRoll})` : ''} · affinity **${h.affinity}** · ${affinityLine(h.affinity, start.sides)} · ${h.blurb}`, '');
  out.push(`Starter deck: ${h.starterDeck.map((k) => getCard(k).name).join(', ')}.`, '');
  out.push('| Card | Cost | Type | Pool | Text | Upgraded |', '|---|---|---|---|---|---|');
  for (const key of CARDS_BY_HERO[hero]) out.push(cardRow(key, hero));
  const shared = [...REWARD_POOLS[hero].common, ...REWARD_POOLS[hero].uncommon, ...REWARD_POOLS[hero].rare]
    .filter((k) => CARDS_BY_HERO.shared.includes(k));
  if (shared.length) out.push('', `Shared cards in this pool: ${shared.map((k) => `${getCard(k).name} (${rarityIn(hero, k)})`).join(', ')}.`);
  out.push('');
}

out.push('## Shared cards', '', '| Card | Cost | Type | Pool | Text | Upgraded |', '|---|---|---|---|---|---|');
for (const key of CARDS_BY_HERO.shared) out.push(cardRow(key, ''));
out.push('');

out.push('## Notes for review', '');
for (const [key, def] of Object.entries(CARDS)) {
  if (def.identicalUpgrade) out.push(`- ⚠ **${def.name}+** — identical upgrade. ${def.identicalUpgrade}`);
}
out.push('');

out.push('## Starter-deck balance (Floor 1)', '');
out.push('Each hero\'s unmodified starter deck at full HP, 300 seeded fights per cell, played by a simple');
out.push('greedy agent (rerolls a missed affinity, then plays random affordable cards; never plays into an');
out.push('unmet condition). Win % / average turns to win / average HP lost in a win. A human should beat these.', '');
const floor = FLOOR_POOLS[1];
const enemyIds = [...floor.easy, ...floor.standard, ...floor.elite];
out.push(`| Hero | ${enemyIds.map((id) => ENEMIES[id].name + (floor.easy.includes(id) ? ' (easy)' : floor.elite.includes(id) ? ' (elite)' : '')).join(' | ')} |`);
out.push(`|---|${enemyIds.map(() => '---').join('|')}|`);
for (const hero of heroes) {
  const cells = enemyIds.map((id) => {
    const b = balance(hero, id);
    return `${b.win}% / ${b.turns} / ${b.hpLost}`;
  });
  out.push(`| ${HEROES[hero].name} | ${cells.join(' | ')} |`);
}
out.push('');

// ── Per floor (step 3f) ──

/** Average win % of the starter deck across a list of enemies, `n` fights each. */
function poolWin(hero, ids, n) {
  const wins = ids.map((id) => balance(hero, id, n).win);
  return Math.round(wins.reduce((a, b) => a + b, 0) / wins.length);
}

out.push('## Starter-deck balance by floor', '');
out.push('The same agent and the same unmodified starter deck at full HP, now against every floor\'s pools:');
out.push('the win % averaged over the floor\'s five standard enemies and over its two elites, 100 fights');
out.push('each. It measures how steeply the floors climb, not what a real run faces there — by Floor 4 a');
out.push('run has a bigger deck, upgrades and Soul Forge purchases, which the next table includes.', '');
const floors = Object.keys(FLOOR_POOLS).map(Number);
out.push(`| Hero | ${floors.map((f) => `F${f} standard | F${f} elite`).join(' | ')} | Companion bosses |`);
out.push(`|---|${floors.map(() => '---|---').join('|')}|---|`);
for (const hero of heroes) {
  const cells = floors.flatMap((f) => [poolWin(hero, FLOOR_POOLS[f].standard, 100), poolWin(hero, FLOOR_POOLS[f].elite, 100)]);
  const bosses = Object.entries(COMPANION_BOSSES).filter(([k]) => k !== hero).map(([, id]) => id);
  out.push(`| ${HEROES[hero].name} | ${cells.map((w) => `${w}%`).join(' | ')} | ${poolWin(hero, bosses, 100)}% |`);
}
out.push('');

// ── Full runs (step 3f) ──
// The same greedy agent for every fight, and a fixed policy between fights, so the only thing that
// varies between heroes is the hero. It takes a random offered card, rests to heal below 60% HP and
// otherwise upgrades a random card, buys the first affordable Soul Forge offer, and always takes
// the plain door. It never shops, takes a Magic Door or the Mirror, or swaps its die, so the column
// reads as a floor on a real run rather than a forecast of one.

const FULL_RUNS = 200;
const STALL_TURNS = 100;

function fullRun(hero, seed) {
  const run = createRun({ heroKey: hero, seed });
  const rng = createRng(seed * 7717);
  let reached = 0;
  for (let guard = 0; guard < 5000; guard++) {
    reached = Math.max(reached, run.floor);
    const screen = run.state.screen;
    if (screen === 'end') break;
    if (screen === 'pathSelect') choosePath(run, pick(rng, ['A', 'B', 'C']));
    else if (screen === 'doors') chooseDoor(run, doorOptions(run).options[0].id);
    else if (screen === 'combat') {
      const c = run.combat;
      while (c.phase === 'player' && c.turn < STALL_TURNS) agentTurn(c, rng);
      if (c.phase === 'player') return { reached, won: false, stalled: true };
      finishCombat(run);
    } else if (screen === 'reward') {
      const cards = run.state.reward.cards;
      if (cards.length) takeCardReward(run, pick(rng, cards).key);
      else skipCardReward(run);
    } else if (screen === 'rest') {
      const o = restOptions(run);
      if (o.canHeal && run.hp < run.maxHp * 0.6) restHeal(run);
      else if (o.upgradable) restUpgrade(run, pick(rng, run.deck.filter(canUpgrade)).uid);
      else if (o.canHeal) restHeal(run);
      else if (o.canLeave) restLeave(run);
      else restRemove(run, run.deck[0].uid);
    } else if (screen === 'soulForge') {
      const affordable = run.state.offers.find((id) => soulCost(run, id) <= run.souls);
      if (affordable) soulBuy(run, affordable);
      else soulLeave(run);
    } else if (screen === 'shop') shopLeave(run);
    else if (screen === 'room') leaveRoom(run);
    else if (screen === 'dieCache') leaveDieCache(run);
    else if (screen === 'bossIntro') faceBoss(run);
    else if (screen === 'floorClear') leaveFloorClear(run);
    else throw new Error(`fullRun: unhandled screen ${screen}`);
  }
  return { reached, won: run.state.result === 'victory', stalled: false };
}

out.push('## Full runs', '');
out.push(`${FULL_RUNS} seeded runs per hero, start to finish, with the same agent in every fight and a fixed`);
out.push('policy between them: take a random offered card, rest to heal below 60% HP or else upgrade, buy');
out.push('the first affordable Soul Forge offer, always take the plain door. It never shops, uses a Magic');
out.push('Door or the Mirror, or changes its die. "Reached" counts runs that got to at least that floor;');
out.push(`"stalled" is a fight that ran past ${STALL_TURNS} turns. A human should do far better; the gap between`);
out.push('heroes is the useful part.', '');
out.push('| Hero | Reached F2 | Reached F3 | Reached F4 | Cleared F4 | Stalled |');
out.push('|---|---|---|---|---|---|');
const fullRuns = {};
for (const hero of heroes) {
  const results = Array.from({ length: FULL_RUNS }, (_, i) => fullRun(hero, i + 1));
  const pct = (fn) => `${Math.round((results.filter(fn).length / FULL_RUNS) * 100)}%`;
  fullRuns[hero] = results;
  out.push(`| ${HEROES[hero].name} | ${pct((r) => r.reached >= 1)} | ${pct((r) => r.reached >= 2)} | ${pct((r) => r.reached >= 3)} | ${pct((r) => r.won)} | ${pct((r) => r.stalled)} |`);
}
out.push('');

writeFileSync(new URL('../CARDS.md', import.meta.url), out.join('\n'));
console.log(`CARDS.md written: ${total} cards.`);
